#server:
#  port: 9527

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr=127.0.0.1:8848

    gateway:
      routes:
        - id: baidu
          uri: https://example.org
          predicates:
            - Before=2021-01-20T17:42:47.789-07:00[America/Denver]
            - Path=/red
        - id: consumer
          uri: http://localhost:8070/demo/1
          predicates:
            - Before=2021-01-20T17:42:47.789-07:00[America/Denver]
            - Path=/demo/{string}

management:
  endpoints:
    web:
      exposure:
        include: '*'